name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run:
        mkdir downloads
        mvn -B package --file pom.xml
        cp /home/runner/work/amazon-codeguru-reviewer-sample-app/amazon-codeguru-reviewer-sample-app/target/Guru-Sample-application-0.0.1-SNAPSHOT.jar downloads/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads  

    # Extra step requied for private beta
    - name: Checkout the action from a private repository
      uses: actions/checkout@v2
      with:
        repository: aws-actions/codeguru-reviewer
        ref: refs/heads/main
        ssh-key: ${{ secrets.SSH_KEY }}
        path: ./.github/actions/codeguru-reviewer

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2 #AWS region where you want to use CodeGuru

    - name: AWS CodeGuru Reviewer Security Scanner
      uses: ./.github/actions/codeguru-reviewer 
      with:
        src-root: src/main/java # Java source code root
        build-root: target # build artifact(s) directory

    - name: Upload review result
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json

